### ISSUE TITLE
Add example data to the package

### ISSUE THREAD

**Issue by JoFAM** [CenterForStatistics-UGent/xnet#13]
The data of Sarah could possibly used as example data if she agrees on that. Otherwise another (simple) dataset needs to be added to be used in the examples of the documentation.

@MichielStock any idea on a dataset or do we just use the data of Sarah?

**Comment by MichielStock** [comment]
Use one of those provided in my example (i.e. protein-ligand network). Do not use the one of Sarah, since we do not own it.

**Comment by JoFAM** [comment]
@MichielStock is there a description of that data available somewhere, or a reference? 
Packages for CRAN have to be publication-grade, hence...

The other problem is that the similarity matrices are not symmetric (eg nr_simmat_dg is not a symmetric matrix).

**Comment by MichielStock** [comment]
Reference:
```
@article{Yamanishi2008a,
author = {Yamanishi, Y. and Araki, M. and Gutteridge, A. and Honda, W. and Kanehisa, M.},
journal = {Bioinformatics},
number = {13},
pages = {i232--i240},
title = {{Prediction of drug-target interaction networks from the integration of chemical and genomic spaces}},
volume = {24},
year = {2008}
}
```

**Comment by JoFAM** [comment]
None of the G matrices (dc information) turn out to be symmetric, so example data gives errors when using tskrr(). Reason is that tskrr() does sanity checks to see whether we are dealing with sensible input. And a non-symmetric kernel matrix doesn't make sense.

Possible solutions:
1. New example data from somewhere.
2. use graphkernels package and some Bioconductor packages to reconstruct similarity matrices without having to rely on SIMCOMP. 

2) is a LOT more work, but can be a very nice illustration on how to use the kernel options in R to do a decent analysis.

**Comment by JoFAM** [comment]
Mailed author of original paper for more explanation. Email address mentioned on the publication no longer exists.

**Comment by JoFAM** [comment]
Solved thanks to fmcsR. Added data and explanation of how we obtained it (including help file) with commit  d229c3f
