### ISSUE TITLE
CITATION file needed

### ISSUE THREAD

**Issue by JoFAM** [CenterForStatistics-UGent/xnet#22]

**Comment by JoFAM** [comment]
@MichielStock Kan ik de referentie naar jouw paper al in het package steken, of is de exacte publicatie nog niet bekend?

**Comment by JoFAM** [comment]
Bump @MichielStock voor de referenties naar de papers die moeten worden geupdated.

**Comment by MichielStock** [comment]
Welke file?

**Comment by JoFAM** [comment]
Je mag ze gewoon hier in de issue toevoegen. Of als je het ineens in de package wil steken, kan je inst/CITATION aanpassen. 

https://github.com/CenterForStatistics-UGent/xnet/blob/master/inst/CITATION

**Comment by MichielStock** [comment]
```
M. Stock, T. Pahikkala, A. Airola, B. De Baets and W. Waegeman, A comparative study of pairwise learning methods based on Kernel Ridge Regression, Neural Computation 30 (2018), 2245-2283.

M. Stock, T. Pahikkala, A. Airola, W. Waegeman and B. De Baets, Algebraic shortcuts for leave-one-out cross-validation in supervised network inference, Briefings in Bioinformatics, accepted Sep 2018.
```

**Comment by JoFAM** [comment]
Done in commit  816ebf9

Used official doi for the latter, that one is published in october.
