### ISSUE TITLE
Calculation prediction for new data with homogenous networks. 

### ISSUE THREAD

**Issue by JoFAM** [CenterForStatistics-UGent/xnet#29]
When I have new vertices I want to predict for in a homogenous network, what is the actual input that should be given, and what does one expect as output?

The predictions are calculated as `K %*% Weights %*% t(K)` now for homogenous networks. When using `K %*% Weights %*% K` you get incompatible dimensions when K isn't symmetric. But I'm not sure if any of that actually makes sense.

Say there's 5 vertices used to fit the model, and I have 3 new ones : 

 - K should be 3 * 8
 - K should be 8 * 8

As output, I expect : 

 - a 3 * 8 matrix giving the predictions for every combination of old and new vertices
 - a 3 * 3 matrix giving the predictions for only the new vertices (that's how it's implemented now)
 - something else

@MichielStock how do you want it to be?

**Comment by MichielStock** [comment]
For a new vertex `v`, you should give a vector `k=c(k(v1,v),...,k(vn,v)` with `v1,...,vn` the vertices of the training data, then the vector of predictions with new predictions 

```
k %*% W %*% K
```
This is (skew)-symmetric where appropriate, by design.

**Comment by JoFAM** [comment]
@MichielStock and K is the original kernel matrix then I presume?

**Comment by MichielStock** [comment]
Yes!

**Comment by JoFAM** [comment]
Labelled bug, as I'm quite confident new predictions are not calculated correctly right now. Urgent!

**Comment by JoFAM** [comment]
Is fixed, but still needs a few examples in the help page to guide people.

**Comment by JoFAM** [comment]
Finished with : cc16adb
