### ISSUE TITLE
Tune function needs to be corrected / expanded

### ISSUE THREAD

**Issue by JoFAM** [CenterForStatistics-UGent/xnet#31]
After review I think that tune doesn't update the predictions correctly. 

To do : 

 - [x] check prediction calculation
 - [x] add possibility to give AUC ( @MichielStock asked for this )

**Comment by JoFAM** [comment]
Correction to tune function : 01fbd02 

It was indeed very, very wrong. If you run the example for `tune()` now, you actually see a minimum MSE for a reasonable combination of lambdas.

**Comment by MichielStock** [comment]
How does the tune work? You should be able to give
- leave-out strategy/setting
- error function `f(Y, F) -> real` which should be minimized

**Comment by JoFAM** [comment]
@MichielStock you give a `tskrr` result as the model to be tuned. This will automatically detect whether it is homogenous or heterogenous. Then you can use the argument 'exclusion' to specify the leave-out strategy (interaction, row, column or both). See also `?tune`. I still have to adapt to pass the error function itself, working on that now.

**Comment by JoFAM** [comment]
Now you can specify a function using the argument `fun`. It should take two matrices.

Done in commit https://github.com/CenterForStatistics-UGent/xnet/commit/d9dce1a8dd6d5244e302b64fdf0555b7604f4c55

**Comment by JoFAM** [comment]
Some loss functions are now provided in the package. See `?loss_functions`

Done in commit de30b80
