### ISSUE TITLE
Unit test linear filter can't work.

### ISSUE THREAD

**Issue by JoFAM** [CenterForStatistics-UGent/xnet#35]
In the example code, the LOO unit test for a linear filter is given as:

```
  FlooI <- loo.I.lf(model.lf)

  Ytilde <- Y
  Y[i,j] <- FlooI[i,j]
  F.lf.min.ij <- train.linear.filter(Ytilde)$F
```
This doesn't work at all. I also can't find the actual shortcuts in the paper, so I'm not sure that the shortcut itself isn't flawed @MichielStock

**Comment by JoFAM** [comment]
I've implemented a naive LOO function as follows : 

```
testLOO <- function(Y,alpha){
  
  Ya <- Y*alpha[1]
  res <- matrix(NA, nrow = nrow(Y), ncol = ncol(Y))
  
  for(i in seq_len(nrow(Y))){
    for(j in seq_len(ncol(Y))){
      res[i,j] <- Ya[i,j] +
        mean(Y[-i,j])*alpha[2] + #column mean minus ith row
        mean(Y[i,-j])*alpha[3] + #row mean minus jth column
        mean(Y[-i,-j])*alpha[4]  # mean minus observation
    }
  }
  return(res)
}
```
If I compare the results with the outcome of LOO, the result is not even close. I've tried all variations on replacement of the value that has to be multiplied by `alpha[1]` instead of `Ya[i,j]`, but I can't wrap my head around it.

Replacing by 0 works, tested with following naive implementation. : 

```
testLOO0 <- function(Y,alpha){

  res <- matrix(NA, nrow = nrow(Y), ncol = ncol(Y))

  for(i in seq_len(nrow(Y))){
    for(j in seq_len(ncol(Y))){
      Ytilde <- Y
      Ytilde[i,j] <- 0
      res[i,j] <- 0 +
        mean(Ytilde[,j])*alpha[2] + #column mean
        mean(Ytilde[i,])*alpha[3] + #row mean
        mean(Ytilde)*alpha[4]  # mean
    }
  }
  return(res)

}

```

**Comment by MichielStock** [comment]
For setting I you basically have two cases:

- removing (i,j) from the dataset and making a prediction using a model based on this dataset (leave-one-out)
- setting (i,j) to zero and making a prediction  using a model based on this dataset (zero-one-out).

The former can be done using Eq. (4) in the [paper](https://www.nature.com/articles/srep45908). For the zero-one-out, you just have to discard the denominator. Both are different, so clearly the computation is the latter (replacing interactions with 0).

Given that leave-one-out is actually more or less defined by this formula, I am not 100% sure if it makes sense to do this in a naive setting. The formula is correct.

**Comment by JoFAM** [comment]
Stupid idiot me forgot that `Y[-i,-j]` drops both the ith row and the jth column entirely. So obivously that `testLOO` doesn't work, it doesn't calculate the correct mean. Correct `testLOO` function added, which revealed a dimension reversal in `loo.i.lf` and `loo.i0.lf` . 

Found my sanity back in commit  4e39625
