### ISSUE TITLE
Update description file

### ISSUE THREAD

**Issue by JoFAM** [CenterForStatistics-UGent/xnet#4]
- [x] set authors
- [ ] create correct description field
- [x] add bug tracker
- [x] add website (can be a github page, still to be decided).

**Comment by JoFAM** [comment]
authors, bug tracker and website via commit https://github.com/CenterForStatistics-UGent/xnet/commit/e7be2d3d3a966e3a9b329a412bb3947e182b4be6

**Comment by JoFAM** [comment]
@MichielStock Als je mij een betere omschrijving van de package kan geven in 1 paragraaf, voeg ik die wel toe. Of als je die zelf toevoegt, zorg ervoor dat elke regel onder Description: begint met minstens 4 spaties. Anders geeft die building errors.

**Comment by MichielStock** [comment]
In orde

**Comment by JoFAM** [comment]
@MichielStock kan je in de devel branch werken? Dan moet ik niet elke keer een aantal conflicts oplossen ;-) 

changes pulled in devel

**Comment by MichielStock** [comment]
@JoFAM sorry! Dacht dat dat geen conflicts zou geven.

Is er nog iets wat ik kan doen of bij kan helpen? Ik ben het wat uit het oog verloren. Zie niet direct issues die ik kan verhelpen.

**Comment by JoFAM** [comment]
@MichielStock ben zelf momenteel de pim aan het afwerken en les aan het geven, dus ik ben nog niet veel verder geraakt. Staat deze week op de planning, dus tegen het einde van de week gaat er al wel een en ander te checken zijn. Ik houd je op de hoogte!
