### ISSUE TITLE
Names CV homogeneous

### ISSUE THREAD

**Issue by MichielStock** [CenterForStatistics-UGent/xnet#42]
For homogeneous, the two options for `exclusion=` should be `edges` and `vertices`, as in the paper.

**Comment by JoFAM** [comment]
Needs the following : 

 - [ ] change in the internal function
 - [ ] change in the loo function and get_loo_fun
 - [ ] check all validation functions (eg tskrrTune check needs splitting to homogeneous and heterogeneous)
 - [ ] check all functions that pass arguments to loo() or get_loo_fun()
 - [ ] update all help files of relevant functions
 - [ ] add breaking changes note to news.md

**Comment by JoFAM** [comment]
HOLD YOUR HORSES! This will be just adding edges and vertices as extra options, and translate to interaction and both.

**Comment by JoFAM** [comment]
Done in edb70b9fb90780f8551a7cee8afb7ab89920f11f
